/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hanto
 */
public class Jacobi extends javax.swing.JFrame {
    int n;
    double A[][];
    double B[];
    /**
     * Creates new form Jacobi
     */
    public Jacobi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFinal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatriz = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Respuesta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tbl2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tbl5 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tbl1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Tbl3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Tbl6 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        BtnRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Método de Jacobi ");

        TablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane1.setViewportView(TablaFinal);

    jLabel2.setText(" Dimensiones de la matriz cuadrada :");

    txtN.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNActionPerformed(evt);
        }
    });
    txtN.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtNKeyTyped(evt);
        }
    });

    tblMatriz.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    tblMatriz.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            tblMatrizFocusGained(evt);
        }
    });
    tblMatriz.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            tblMatrizKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            tblMatrizKeyTyped(evt);
        }
    });
    jScrollPane2.setViewportView(tblMatriz);

    btnCrear.setText("Crear matriz");
    btnCrear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCrearActionPerformed(evt);
        }
    });

    Tbl4.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    )

    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane3.setViewportView(Tbl4);

    jLabel3.setText("B:");

    Respuesta.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "B"
        }
    ));
    Respuesta.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            RespuestaFocusGained(evt);
        }
    });
    Respuesta.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            RespuestaKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            RespuestaKeyTyped(evt);
        }
    });
    jScrollPane4.setViewportView(Respuesta);

    jLabel4.setText("D:");

    Tbl2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    )

    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane5.setViewportView(Tbl2);

    jLabel5.setText("(L+U):");

    Tbl5.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    )

    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane6.setViewportView(Tbl5);

    jLabel6.setText("D^-1");

    Tbl1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            ""
        }
    )

    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane7.setViewportView(Tbl1);
    if (Tbl1.getColumnModel().getColumnCount() > 0) {
        Tbl1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
    }

    jLabel7.setText("D^-1b:");

    Tbl3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    )

    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane8.setViewportView(Tbl3);

    jLabel8.setText("-(L+U):");

    Tbl6.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    )

    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane9.setViewportView(Tbl6);

    jLabel9.setText("D^-1-(L+U):");

    BtnRespuesta.setText("Resolver");
    BtnRespuesta.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            BtnRespuestaFocusGained(evt);
        }
    });
    BtnRespuesta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnRespuestaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(543, 543, 543)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnRespuesta))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(btnCrear))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel7)))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(34, 34, 34))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(170, 170, 170))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrear))
                                    .addGap(28, 28, 28))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(15, 15, 15)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(BtnRespuesta)
            .addContainerGap(15, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1298, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 6, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        n = Integer.parseInt(txtN.getText());
        if (n > 7) {
            JOptionPane.showMessageDialog(rootPane, "No se puede generar una matriz de orden superior al 7");
        }else{
        int[][] matriz = new int [n][n];
        
        this.mostrarMatriz(matriz, n);
        this.mostrarRepuesta(matriz, n);
        this.MatrizTbl1(matriz, n);
        this.MatrizTbl2(matriz, n);
        this.MatrizTbl3(matriz, n);
        this.MatrizTbl4(matriz, n);
        this.MatrizTbl5(matriz, n);
        this.MatrizTbl6(matriz, n);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
    if(Character.isLetter(validar)){
    getToolkit().beep();
    evt.consume();

    JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
    }
    
    }//GEN-LAST:event_txtNKeyTyped

    private void tblMatrizKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMatrizKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
    if(Character.isLetter(validar)){
    getToolkit().beep();
    evt.consume();

    JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
    }
    }//GEN-LAST:event_tblMatrizKeyTyped

    private void RespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestaKeyTyped
        // TODO add your handling code here:
            char validar=evt.getKeyChar();
    if(Character.isLetter(validar)){
    getToolkit().beep();
    evt.consume();

    JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
    }
    }//GEN-LAST:event_RespuestaKeyTyped

    private void BtnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRespuestaActionPerformed
        // TODO add your handling code here:
        A= new double[n][n];
        B = new double[n];


        if ((MatrizPrincipalLlenar() && MatrizRespLlenar())) {
            for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                A[i][j] = Double.parseDouble(tblMatriz.getValueAt(i, j).toString());
            }
                B[i] = Double.parseDouble(Respuesta.getValueAt(i, 0).toString());
        }
        }
    }//GEN-LAST:event_BtnRespuestaActionPerformed

    private void tblMatrizFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblMatrizFocusGained
        // TODO add your handling code here:
        if (tblMatriz.isEditing()) {
            tblMatriz.getCellEditor().stopCellEditing();
        }
    }//GEN-LAST:event_tblMatrizFocusGained

    private void RespuestaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RespuestaFocusGained
        // TODO add your handling code here:
        if (Respuesta.isEditing()) {
            Respuesta.getCellEditor().stopCellEditing();
        }
    }//GEN-LAST:event_RespuestaFocusGained

    private void BtnRespuestaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BtnRespuestaFocusGained
        // TODO add your handling code here:
        if (tblMatriz.isEditing()) {
            tblMatriz.getCellEditor().stopCellEditing();
        }else if (Respuesta.isEditing()) {
           Respuesta.getCellEditor().stopCellEditing();
        }
    }//GEN-LAST:event_BtnRespuestaFocusGained

    private void tblMatrizKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMatrizKeyPressed
        // TODO add your handling code here:
        char val = evt.getKeyChar();

        if ((val<'0' || val>'9') && val>'-' ) evt.consume();
    }//GEN-LAST:event_tblMatrizKeyPressed

    private void RespuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestaKeyPressed
        // TODO add your handling code here:
        char val = evt.getKeyChar();

        if ((val<'0' || val>'9') && val>'-' ) evt.consume();
    }//GEN-LAST:event_RespuestaKeyPressed

    /**
     * @param args the command line arguments
     */
    public void mostrarMatriz(int matriz[][], int n){
       DefaultTableModel model= (DefaultTableModel)tblMatriz.getModel();
      
        model.setRowCount(n);
        model.setColumnCount(n);
        

    }
    
    
    public void mostrarRepuesta(int matriz[][],int n){
        DefaultTableModel model= (DefaultTableModel)Respuesta.getModel();
        model.setRowCount(n);
        model.setColumnCount(1);
    }
    
    public void MatrizTbl1(int matriz[][], int n){
        DefaultTableModel model= (DefaultTableModel)Tbl1.getModel();
        model.setRowCount(n);
        model.setColumnCount(1);
    }
    
    public void MatrizTbl2(int matriz[][], int n){
        DefaultTableModel model= (DefaultTableModel)Tbl2.getModel();
        model.setRowCount(n);
        model.setColumnCount(n);
    }
    
    public void MatrizTbl3(int matriz[][], int n){
        DefaultTableModel model= (DefaultTableModel)Tbl3.getModel();
        model.setRowCount(n);
        model.setColumnCount(n);
    }
    
    public void MatrizTbl4(int matriz[][], int n){
        DefaultTableModel model= (DefaultTableModel)Tbl4.getModel();
        model.setRowCount(n);
        model.setColumnCount(n);
    }
    
    public void MatrizTbl5(int matriz[][], int n){
        DefaultTableModel model= (DefaultTableModel)Tbl5.getModel();
        model.setRowCount(n);
        model.setColumnCount(n);
    }
    
    public void MatrizTbl6(int matriz[][], int n){
        DefaultTableModel model= (DefaultTableModel)Tbl6.getModel();
        model.setRowCount(n);
        model.setColumnCount(n);
    }
    
 
    public void Respuesta() {
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jacobi().setVisible(true);
            }
        });
    }
    
    public boolean MatrizPrincipalLlenar(){

    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            if (tblMatriz.getValueAt(i, j) ==  null) {
                JOptionPane.showMessageDialog(rootPane, "No puede haber valores vacíos en la matriz de valores", "Elementos faltantes", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
    }
    return true;
}

public boolean MatrizRespLlenar(){

    for (int i = 0; i < n; i++) {
        if (Respuesta.getValueAt(i, 0) ==  null) {
            JOptionPane.showMessageDialog(rootPane, "No puede haber valores vacíos en la matriz de resultados", "Elementos faltantes", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    return true;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRespuesta;
    private javax.swing.JTable Respuesta;
    private javax.swing.JTable TablaFinal;
    private javax.swing.JTable Tbl1;
    private javax.swing.JTable Tbl2;
    private javax.swing.JTable Tbl3;
    private javax.swing.JTable Tbl4;
    private javax.swing.JTable Tbl5;
    private javax.swing.JTable Tbl6;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tblMatriz;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
